<?
$name="Form";

$include_php=array(
  "inc/form.php",
  "inc/functions.php",
  "inc/form_element.php",
  "inc/form_element_array.php",
  "inc/form_element_checkbox.php",
  "inc/form_element_form.php",
  "inc/form_element_radio.php",
  "inc/form_element_text.php",
);
$include_js=array(
  "inc/functions.js",
  "inc/form.js",
  "inc/form_element.js",
  "inc/form_element_text.js",
  "inc/form_element_radio.js",
  "inc/form_element_form.js",
  "inc/form_element_checkbox.js",
  "inc/form_element_array.js",
);
$include_css=array(
  "inc/form.css",
  "inc/form_element_array.css",
);
