<?
$name="Form";

$id="modulekit-form";

$include_php=array(
  "inc/form.php",
  "inc/functions.php",
  "inc/form_element.php",
  "inc/form_element_array.php",
  "inc/form_element_checkbox.php",
  "inc/form_element_form.php",
  "inc/form_element_radio.php",
  "inc/form_element_text.php",
  "inc/form_element_textarea.php",
  "inc/form_element_color.php",
  "inc/form_element_password.php",
  "inc/form_element_keywords.php",
  "inc/form_element_json.php",
  "inc/form_element_unsupported.php",
  "inc/form_element_select.php",
  "inc/form_element_file.php",
  "inc/form_element_directory.php",
  "inc/form_element_numeric.php",
);
$include_js=array(
  "inc/functions.js",
  "inc/form.js",
  "inc/form_element.js",
  "inc/form_element_text.js",
  "inc/form_element_textarea.js",
  "inc/form_element_radio.js",
  "inc/form_element_form.js",
  "inc/form_element_checkbox.js",
  "inc/form_element_array.js",
  "inc/form_element_color.js",
  "inc/form_element_password.js",
  "inc/form_element_keywords.js",
  "inc/form_element_json.js",
  "inc/form_element_unsupported.js",
  "inc/form_element_select.js",
  "inc/form_element_numeric.js",
);
$include_css=array(
  "inc/form.css",
  "inc/form_element_array.css",
  "inc/form_element_keywords.css",
);
