module.exports = {
  array: require('./form_element_array'),
  autocomplete: require('./form_element_autocomplete'),
  'boolean': require('./form_element_boolean'),
  checkbox: require('./form_element_checkbox'),
  color: require('./form_element_color'),
  date: require('./form_element_date'),
  display: require('./form_element_display'),
  file: require('./form_element_file'),
  fixed: require('./form_element_fixed'),
  form_chooser: require('./form_element_form_chooser'),
  form: require('./form_element_form'),
  hash: require('./form_element_hash'),
  hidden: require('./form_element_hidden'),
  intermediate_text: require('./form_element_intermediate_text'),
  json: require('./form_element_json'),
  keywords: require('./form_element_keywords'),
  label: require('./form_element_label'),
  numeric: require('./form_element_numeric'),
  password: require('./form_element_password'),
  radio: require('./form_element_radio'),
  select: require('./form_element_select'),
  select_other: require('./form_element_select_other'),
  'switch': require('./form_element_switch'),
  textarea: require('./form_element_textarea'),
  text: require('./form_element_text')
}
